version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.6

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies (CI mode)
          command: |
            npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  compile:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: |
            npm run build

  check-gql-schema:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Generate GQL Schema
          command: |
            npm run schemas:gql
      - run:
          name: Check schema was not chaged
          command: |
            git diff --exit-code

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lint code
          command: |
            npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: |
            npm run test

  build-image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t ragelo/apollo-server-boilerplate:$CIRCLE_SHA1 .
      - run:
          name: Push image to the registry
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              docker image tag ragelo/apollo-server-boilerplate:$CIRCLE_SHA1 ragelo/apollo-server-boilerplate:$CIRCLE_BRANCH
              echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
              docker push ragelo/apollo-server-boilerplate:$CIRCLE_SHA1
              docker push ragelo/apollo-server-boilerplate:$CIRCLE_BRANCH
            fi

workflows:
  version: 2
  default:
    jobs:
      - install
      - compile:
          requires:
            - install
      - check-gql-schema:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-image:
          requires:
            - compile
            - check-gql-schema
            - lint
            - test


